# Generated by Django 4.2.3 on 2023-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bookmark',
            field=models.IntegerField(default=0, verbose_name='북마크개수'),
        ),
    ]
