# Generated by Django 4.2.3 on 2023-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0003_alter_recommend_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='ifbookmark',
            field=models.BooleanField(default=False, verbose_name='북마크여부'),
        ),
        migrations.AddField(
            model_name='request',
            name='ifbookmark',
            field=models.BooleanField(default=False, verbose_name='북마크여부'),
        ),
    ]
