# Generated by Django 4.2.3 on 2023-07-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlistApp', '0004_recommend_ifbookmark_request_ifbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateField(auto_now_add=True, verbose_name='작성일')),
                ('bookmark', models.IntegerField(default=0, verbose_name='북마크개수')),
                ('ifbookmark', models.BooleanField(default=False, verbose_name='북마크여부')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='myBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateField(auto_now_add=True, verbose_name='작성일')),
                ('bookmark', models.IntegerField(default=0, verbose_name='북마크개수')),
                ('ifbookmark', models.BooleanField(default=False, verbose_name='북마크여부')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
